#!/bin/bash

- name: varibels at task level
  hosts: localhost
  user: centos
  become: yes
  connection: ssh
  vars:
   NAME: CHANDRIKA GRANDHI
   COURSE: ISBA
   COUNTRY: USA.
   COLLEGE: Park University
  tasks:
  - name: testing at peaks celebration of variabels
    ansible.builtin.debug:
    msg: "my name is {{NAME}},i am studying {{COURSE}} at {{COLLEGE}}in {{COUNTRY}}"