#!/bin/bash

- name: variabels from files
  hosts: localhost
  user: centos
  become: yes
  connection: ssh
  vars_files:
  - variabels.yaml
  tasks:
  - name: testing variabels from files
    ansible.builtin.debug:
      msg: "i am taking {{Course}} from {{Trainer}}"