#!/bin/bash

- name: traying file from inventory
  hosts: localhost
  user: centos
  become: yes
  connection: ssh
  tasks:
  - name: inventory files
    ansible.builtin.debug:
      msg: "my {{Course}} is {{Trainer}}"