- name: installing packages
  hosts: localhost
  user: centos
  become: yes
  connection: ssh
  tasks:
  - name: installing git,mysql
    ansible.builtin.package:
     name: "{{item}}"
     state: present
    loop:
    - git
    - mysql 
    - maven