- name: loops with pak
  hosts: localhost
  user: centos
  become: yes
  connection: shh
  tasks:
  - name: loops with pack2
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.sate}}"
      loop:
      - {name: 'mysql', state: 'present'}
      - {name: 'git', state: 'absent'}
      - {name: 'maven', state: 'absent'}
