- name: loops
  hosts: localhost
  user: centos
  become: yes
  connection: ssh
  password: "DevOps321"
  tasks:
  - name: looops
    ansible.builtin.debug:
     msg: "hello {{item}}"
    loop: 
    - ramesh
    - suresh
    - robert 
    - gopi
    - chandu
