- name: loops with pak
  hosts: localhost
  user: centos
  become: yes
  connection: shh
  tasks:
  - name: loops with pack2
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'absent'}
    - {name: 'maven', state: 'absent'}
    - {name: 'mysql', state: 'absent'}