- name: ping playbook 
  hosts: localhost
  tasks:
  - name: ping the server
    ping:

  - name: print the message
    debug:
      msg: "hello DevOps"
    tags:
    - devops

  - name: calling aws
    debug:
      msg: "hello aws"
    tags:
    - aws  


